# Generated by Django 3.1 on 2020-10-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myGroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='students_number',
        ),
    ]
